spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nerdket?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50

logging.level:
  org.hibernate.SQL: debug

server.servlet.session:
  tracking-modes: cookie
  timeout: 1800
